# Generated by Django 6.0.2 on 2026-04-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='review_status_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='EvidenceValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='compliance.assessmentresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
