# Generated by Django 6.0.2 on 2026-04-05 10:59

import django.db.models.deletion
from collections import defaultdict

from django.conf import settings
from django.db import migrations, models


def forwards_create_runs_and_link(apps, schema_editor):
    AssessmentRun = apps.get_model('compliance', 'AssessmentRun')
    AssessmentResult = apps.get_model('compliance', 'AssessmentResult')
    grouped = defaultdict(list)
    for row in AssessmentResult.objects.select_related('control__domain').iterator():
        sid = row.control.domain.standard_id
        grouped[(row.user_id, sid)].append(row.pk)
    for (uid, std_id), pks in grouped.items():
        run = AssessmentRun.objects.create(
            user_id=uid,
            standard_id=std_id,
            title='Default assessment',
        )
        AssessmentResult.objects.filter(pk__in=pks).update(assessment_run_id=run.id)


def backwards_unlink_runs(apps, schema_editor):
    AssessmentRun = apps.get_model('compliance', 'AssessmentRun')
    AssessmentResult = apps.get_model('compliance', 'AssessmentResult')
    AssessmentResult.objects.all().update(assessment_run_id=None)
    AssessmentRun.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_smart_evidence_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='compliance.standard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.assessmentrun'),
        ),
        migrations.RunPython(forwards_create_runs_and_link, backwards_unlink_runs),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.assessmentrun'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control'), name='compliance_assessmentresult_unique_run_control'),
        ),
    ]
